#!/usr/bin/env bash
# gen-secrets.sh — generate strong random values for all required secrets
# and write them into .env (if it doesn't already exist).
#
# Usage:
#   ./scripts/gen-secrets.sh          # writes .env in project root
#   ./scripts/gen-secrets.sh --force  # overwrite existing .env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/.."
ENV_FILE="$PROJECT_ROOT/backend/.env"

if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "backend/.env already exists. Use --force to overwrite."
  exit 1
fi

rand() { openssl rand -base64 32 | tr -d '/+=' | head -c "${1:-44}"; }

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by gen-secrets.sh on $(date -u +%FT%TZ) ──────────────
# DO NOT commit this file.

# ── Auth ─────────────────────────────────────────────────────────────────
JWT_SECRET=$(rand 44)

# ── Database ─────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=$(rand 32)
DATABASE_URL=postgresql://jlearn:$(rand 32)@postgres:5432/jlearn

# ── SMTP ─────────────────────────────────────────────────────────────────
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
EMAIL_FROM=noreply@yourdomain.com

# ── App ──────────────────────────────────────────────────────────────────
FRONTEND_URL=https://yourdomain.com
CORS_ORIGINS=https://yourdomain.com

# ── Observability (optional) ──────────────────────────────────────────────
SENTRY_DSN=
EOF

echo "Wrote secrets to backend/.env"
echo "Next: fill in SMTP_HOST / SMTP_USER / SMTP_PASS and FRONTEND_URL."
